version: "3.9"

services:
  api:
    build: 
      context: .
      dockerfile: ./API/Dockerfile
    hostname: api
    networks:
      - default
    env_file:
      - ./API/.env
    
  another-api:
    build:
      context: .
      dockerfile: ./AnotherAPI/Dockerfile
    hostname: another-api
    networks:
      - default
    env_file:
      - ./AnotherAPI/.env

  gateway:
    build:
      context: .
      dockerfile: ./Gateway/Dockerfile
    env_file:
      - ./Gateway/.env
    ports:
      - "5000:5000"
    depends_on:
      - api
      - another-api
    networks:
      - default

networks:
  default:
    driver: bridge