version: "3.9"

services:
  api:
    build: 
      context: ..
      dockerfile: ./API/Dockerfile
      args:
        APP_PORT: 5001
        APP_CONFIGURATION: ${APP_CONFIGURATION}
    env_file:
      - .env
    hostname: api
    networks:
      - default
  
  another-api:
    build:
      context: ..
      dockerfile: ./AnotherAPI/Dockerfile
      args:
        APP_PORT: 5002
        APP_CONFIGURATION: ${APP_CONFIGURATION}
    env_file:
      - .env
    hostname: another-api
    networks:
      - default

  gateway:
    build:
      context: ..
      dockerfile: ./Gateway/Dockerfile
      args:
        APP_PORT: 5000
        APP_CONFIGURATION: ${APP_CONFIGURATION}
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - api
      - another-api
    networks:
      - default

networks:
  default:
    driver: bridge